### ISSUE TITLE
Finish multiplayer system

### ISSUE THREAD

**Issue by zenith391** [zenith391/LGGL#1]
Title explains what is planned

**Comment by CristeaAndreiFlavian** [comment]
Almost done!

**Comment by CristeaAndreiFlavian** [comment]
95% Done!

We think the MULTIPLAYER will be done in the next update!

**Comment by CristeaAndreiFlavian** [comment]
98%!!!

**Comment by CristeaAndreiFlavian** [comment]
100% Done!
MULTIPLAYER is LAUNCHED!

#Subject Closed
